// Generated by Selenium IDE
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;


public class TestTest {
    private WebDriver driver;

    // private Map<String, Object> vars;
    //JavascriptExecutor js;
    @BeforeClass

    public void setUp() {
        driver = new ChromeDriver();
        // js = (JavascriptExecutor) driver;
        //vars = new HashMap<String, Object>();
        driver.manage().window().maximize();
        driver.get("https://www.google.com/");
    }

    @Test
    public void test() {
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("WebDriver");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    }

    @AfterClass
    public void tearDown() {
        driver.quit();
    }
}
